travis:
  secure:
    BINSTAR_TOKEN: C1kpEsSDvF7K2p9v+62IBbd9R5CtlUqoUwd5aqDgBGdW6jIAKDPbPaXlNrAf40rMD/CLoZS9uwPDldXFM8DbqEqE+Pw1Hzd3VzYSoeCxL+J4Uc9ly36x0m6CTTJG80YU0qCp9JkQrW4i3KNqICmPwyPyL4yCJtFEWVsfKaWz4rfNXdDKNCI/nIR96gZJ1ywog3Xrz+YQmTYimX8RToOB+qqetjRnt8t3oFX5JwiG/sOUL2K3CU4HEH3W4Ta1DoOku9nnCuYpf90iUB4a5hPUAo6KHJrudxHIkJm9h5F7UHw2N3q/zfgKjL/mLSagOY8rey+WL74hj52ys7kbj2lT75IPFXabXaKoczi7vuAmCvzREmEskILPFhMjNEhDhPDrF8cTh12+fkFXzvkOap+ZGg1eLjFyzSfTMUD0GGgGfcUPMHj1kKvxe+wvy4Iij42bQWAxqoKRCA+obDn1w8SMbQ/r7DU7OEPR9mbe8PVkcGpIoU9EwBSZDAtIinCU5N/o7sGavckwCjF6W995YOllce1/XjaC7EiC1uoEoM+EqSmzXi96fFJm9kQ38EyBeCKg7Pq2zZnbsL6vxZHkZprO7pYuv+xs92VkgjN185nM8GSQT25gq3mLOSuSIqmt/nQZGeFgbNb8+timBcGyRFddHfTGP3pFSJzSMRFpAKIaiDY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
